import os, sys
setTopologyProfile('Compact')
selectTemplate('Oracle HTTP Server (Standalone)')
loadTemplates()
showTemplates()
cd('/')
create("{{ ohs_component_name }}", 'SystemComponent')
cd('SystemComponent/' + '{{ ohs_component_name }}')
set('ComponentType','OHS')
cd('/')
cd('OHS/' + '{{ ohs_component_name }}')
set('ListenAddress','')
set('ListenPort', '{{ ohs_http_port }}')
set('SSLListenPort', '{{ ohs_https_port }}')
cd('/')
create('sc', 'SecurityConfiguration')
cd('SecurityConfiguration/sc')
set('NodeManagerUsername', "{{ ohs_nm_user }}")
set('NodeManagerPasswordEncrypted', "{{ ohs_nm_pswd }}")
setOption('NodeManagerType','PerDomainNodeManager')
setOption('OverwriteDomain', 'true')
writeDomain("{{ ohs_domain_dir }}")
dumpStack()
closeTemplate()
exit()
